ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_treatments_fk
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_provider_npi
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_patient_id
ALTER TABLE RADDATE DROP CONSTRAINT FK_RADDATE_radiology_fk
DROP TABLE PATIENT CASCADE
DROP TABLE TREATMENT CASCADE
DROP TABLE PROVIDER CASCADE
DROP TABLE RADDATE CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
